Repository bigomics/playbase, pull requests merged in 2025-07, with the labels that each got.

#288 Disable e9 feature removal
  R/pgx-check.R
  data/PGX_CHECKS.rda
  dev/PGX_CHECKS.csv
Labels: bug

#291 feat: pcsf highlight single feature
  R/pgx-pcsf.R
Labels: enhancement

#292 Add Perseus-style-imputation
  R/pgx-impute.R
Labels: enhancement

#296 Commented out old, unused playbase R functions.
  NAMESPACE
  R/pgx-cna.R
  R/pgx-grep2.R
  R/pgx-normalize.R
  R/pgx-proteomics.R
  R/pgx-read.R
  man/dot-RGimputation.Rd
  man/fit.weibull2.Rd
  man/imputeMissing.Rd
  man/matrix_combine_p.Rd
  man/perseusImpute.Rd
  man/pgx.barplot.PLOTLY.Rd
  man/pgx.inferCNV.Rd
  man/pgx.run_salmon.Rd
  man/plotMultiPartiteGraph2.Rd
  man/plotPCSF.Rd
  man/plot_lasagna.Rd
  man/prot.medianImpute.Rd
  man/prot.nmfImpute.Rd
  man/silac.calcCopyNumber.Rd
  man/trimgalore_fastq.Rd
Labels: code cleaning

#293 Enable upload and analysis of Olink NPX data
  DESCRIPTION
  NAMESPACE
  R/pgx-pheno.R
  R/pgx-read.R
  man/make_unique_ws.Rd
  man/read_Olink_NPX.Rd
  man/read_Olink_samples.Rd
Labels: enhancement
